### ISSUE TITLE
Add transformer option to rewrite original entry point script tag

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/initialize#10]
Should be called something like `htmlEntryPoint` and take a file path to an html file. It will then search for script tags linking to `entryPoint` and change them to `newEntryPoint`.

**Comment by sigmundch** [comment]
Another option here, we could give the developer the option to replace the original entrypoint. If they don't have a Dart import to `index.dart`, we could move the original `index.dart` to `original_index,dart` and make the new `index.dart` the boostrap file with the new initializers.

**Comment by sigmundch** [comment]
Looking at #11, I don't think that the alternative option should be the only option, I think you are right that having the htmlEntryPoint is a good thing to have. What are your thoughts on also adding the other option though?

**Comment by jakemac53** [comment]
I don't think it makes a big difference which one we do, and I would rather only support one golden path just to reduce confusion. I like the idea of the bootstrap file a bit more just because it leaves all the original dart files completely in tact, so when debugging everything is a bit more intuitive.
