### ISSUE TITLE
Support supplying only an htmlEntryPoint

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/initialize#13]
Assuming there is only one dart script tag, and it lives in the same library as the html file, we can just use that dart file as the entry point and not require it to be specified:

    transformers:
    - initialize:
        entryPoint: web/index.dart
        htmlEntryPoint: web/index.html

becomes just:

    transformers:
    - initialize:
        htmlEntryPoint: web/index.html

**Comment by jakemac53** [comment]
we could also possibly just use `entryPoint` but allow you to pass an html file instead of a dart file, and then do the right thing based on the file extension

**Comment by sigmundch** [comment]
How about we do this by hiding this transformer inside another transformer in `web_components`?

If you write:
```
transformers:
- web_components/initialize:
    entry_point: web/index.html
```

**Comment by sigmundch** [comment]
ah- never mind, I thought initially this was for specifying the entry point for html-initialization, not just plain initialization. Now that I see #10, I see that this was just to update the bootstrap.html

**Comment by jakemac53** [comment]
fixed in https://github.com/dart-lang/static_init/commit/8ff3cf318c18345a5ac9b99e6c315313c11893f6
