### ISSUE TITLE
use ConstantEvaluator for primitive values

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/initialize#22]
When inlining the const constructor of an initializer annotation, we could use ConstantEvaluator to determine if the value is a simple primitive, if so, just write the primitive value (since they are cannonicalized).

This will allow us to support `@HtmlImport` in more cases, since we need to extract the string argument from it.

**Comment by jakemac53** [comment]
In the new plugin architecture which is coming, this won't be an issue. Plugins will have access to the fully resolved AST and can do this on their own as needed.
