### ISSUE TITLE
The `test_package` path dependency results in error message on `pub upgrade`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/initialize#43]
> Error on line 1, column 1 of https://pub.dartlang.org/api/packages/initialize: Invalid description: "test_package" is a relative path, but this isn't a local pubspec.

I only use hosed dependencies in my pubspec.yaml.

**Comment by terrywarwar** [comment]
I get the same also when upgrading to:
```
polymer: ^1.0.0-rc.10
reflectable: ^0.5.0
```

**Comment by jakemac53** [comment]
Ya I don't know what the issue is with this, the error message isn't clear and the path dependency has been there for a long time. Need to file an issue with pub to get more info.

That being said this hasn't actually caused any issues for me?

**Comment by jakemac53** [comment]
I filed https://github.com/dart-lang/pub/issues/1369

**Comment by zoechi** [comment]
Can this be closed?

**Comment by jakemac53** [comment]
yep, thanks
